# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Apple File System (APFS)

obj-$(CONFIG_APFS_FS) += apfs.o

apfs-y := btree.o dir.o extents.o file.o inode.o key.o message.o \
	  namei.o node.o object.o super.o symlink.o unicode.o xattr.o
